### One‑Hot Encoding is a data preprocessing technique used to convert categorical variables into a numerical format that machine learning models can understand. It represents each category as a separate binary column, where a value of 1 indicates the presence of that category and 0 indicates its absence.

- With Pandas

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = {
    'Employee id': [10, 20, 15, 25, 30],
    'Gender': ['M', 'F', 'F', 'M', 'F'],
    'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice']
}

df = pd.DataFrame(data)

categorical_columns = df.select_dtypes(include=['object']).columns.to_list()
print(f"Original Employee Data:\n{df}\n")
# Use pd.get_dummies() to one-hot encode the categorical columns
df_pandas_encoded = pd.get_dummies(df, columns=['Gender', 'Remarks'], drop_first=True)
# df_pandas_encoded = pd.get_dummies(df, columns=categorical_columns, drop_first=True)
print(f"One-Hot Encoded Data using Pandas:\n{df_pandas_encoded}\n")

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = {
    'Employee id': [10, 20, 15, 25, 30],
    'Gender': ['M', 'F', 'F', 'M', 'F'],
    'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice']
}

df = pd.DataFrame(data)

df

   Employee id Gender Remarks
0           10      M    Good
1           20      F    Nice
2           15      F    Good
3           25      M   Great
4           30      F    Nice

In [3]:
categorical_columns = df.select_dtypes(include=['object']).columns.to_list()
categorical_columns

C:\Users\g.peyyala\AppData\Local\Temp\ipykernel_7920\3439882593.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns.to_list()

['Gender', 'Remarks']

In [9]:
# df_pandas_encoded = pd.get_dummies(df, columns=['Gender', 'Remarks'], drop_first=True)
df_pandas_encoded = pd.get_dummies(df, columns=categorical_columns, drop_first=True)
print(f"One-Hot Encoded Data using Pandas:\n{df_pandas_encoded}\n")

One-Hot Encoded Data using Pandas:
   Employee id  Gender_M  Remarks_Great  Remarks_Nice
0           10      True          False         False
1           20     False          False          True
2           15     False          False         False
3           25      True           True         False
4           30     False          False          True

- Using Scikit Learn Library

In [10]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = {'Employee id': [10, 20, 15, 25, 30],
        'Gender': ['M', 'F', 'F', 'M', 'F'],
        'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice'],
        }
df = pd.DataFrame(data)
print(f"Employee data : \n{df}")

categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(df[categorical_columns])

one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))

df_encoded = pd.concat([df, one_hot_df], axis=1)

df_encoded = df_encoded.drop(categorical_columns, axis=1)
print(f"Encoded Employee data : \n{df_encoded}")

Employee data :
   Employee id Gender Remarks
0           10      M    Good
1           20      F    Nice
2           15      F    Good
3           25      M   Great
4           30      F    Nice
Encoded Employee data :
   Employee id  Gender_F  Gender_M  Remarks_Good  Remarks_Great  Remarks_Nice
0           10       0.0       1.0           1.0            0.0           0.0
1           20       1.0       0.0           0.0            0.0           1.0
2           15       1.0       0.0           1.0            0.0           0.0
3           25       0.0       1.0           0.0            1.0           0.0
4           30       1.0       0.0           0.0            0.0           1.0

C:\Users\g.peyyala\AppData\Local\Temp\ipykernel_7920\415824567.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns.tolist()

In [17]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = {'Employee id': [10, 20, 15, 25, 30],
        'Gender': ['M', 'F', 'F', 'M', 'F'],
        'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice'],
        }
df = pd.DataFrame(data)
print(f"Employee data : \n{df}")

Employee data :
   Employee id Gender Remarks
0           10      M    Good
1           20      F    Nice
2           15      F    Good
3           25      M   Great
4           30      F    Nice

In [18]:
categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
categorical_columns

C:\Users\g.peyyala\AppData\Local\Temp\ipykernel_7920\3030423097.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns.tolist()

['Gender', 'Remarks']

In [19]:
encoder = OneHotEncoder(sparse_output=False)
encoder.get_feature_names_out(categorical_columns)

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [13]:
encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(df[categorical_columns])

one_hot_encoded

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

In [14]:
one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))
one_hot_df

   Gender_F  Gender_M  Remarks_Good  Remarks_Great  Remarks_Nice
0       0.0       1.0           1.0            0.0           0.0
1       1.0       0.0           0.0            0.0           1.0
2       1.0       0.0           1.0            0.0           0.0
3       0.0       1.0           0.0            1.0           0.0
4       1.0       0.0           0.0            0.0           1.0

In [15]:
df_encoded = pd.concat([df, one_hot_df], axis=1)
df_encoded

,Employee id,Gender,Remarks,Gender_F,Gender_M,Remarks_Good,Remarks_Great,Remarks_Nice
0,10,M,Good,0.0,1.0,1.0,0.0,0.0
1,20,F,Nice,1.0,0.0,0.0,0.0,1.0
2,15,F,Good,1.0,0.0,1.0,0.0,0.0
3,25,M,Great,0.0,1.0,0.0,1.0,0.0
4,30,F,Nice,1.0,0.0,0.0,0.0,1.0

In [16]:
df_encoded = df_encoded.drop(categorical_columns, axis=1)
print(f"Encoded Employee data : \n{df_encoded}")

Encoded Employee data :
   Employee id  Gender_F  Gender_M  Remarks_Good  Remarks_Great  Remarks_Nice
0           10       0.0       1.0           1.0            0.0           0.0
1           20       1.0       0.0           0.0            0.0           1.0
2           15       1.0       0.0           1.0            0.0           0.0
3           25       0.0       1.0           0.0            1.0           0.0
4           30       1.0       0.0           0.0            0.0           1.0

- End-to-End usage of OneHot Encoder

In [ ]:
# ========================================================
# FILE 1: churn_onehot_only.py
# Method: One-Hot Encoding ONLY (for categorical columns)
# No text processing (CustomerFeedback column is ignored/dropped)
# Beginner-friendly - Minimal steps with detailed comments
# ========================================================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ====================== STEP 1: Generate 150 Records ======================
print("=== STEP 1: Generating 150 synthetic customer records ===")
np.random.seed(42)

n_samples = 150

data = {
    'Gender': np.random.choice(['Male', 'Female'], n_samples),
    'Contract': np.random.choice(['Month-to-month', 'One year', 'Two year'], n_samples, p=[0.55, 0.30, 0.15]),
    'PaymentMethod': np.random.choice(['Electronic check', 'Mailed check', 'Bank transfer', 'Credit card'], n_samples),
    'InternetService': np.random.choice(['DSL', 'Fiber optic', 'No'], n_samples, p=[0.35, 0.50, 0.15]),
    'Tenure': np.random.randint(1, 73, n_samples),
    'MonthlyCharges': np.round(np.random.uniform(20, 120, n_samples), 2),
    'CustomerFeedback': np.random.choice([
        "Great service", "Poor connection", "Excellent support", "Billing issues",
        "Love the pricing", "Slow internet", "Happy overall", "Too expensive"
    ], n_samples)
}

df = pd.DataFrame(data)

# Create target (Churn)
high_churn = (df['Tenure'] < 12) | (df['MonthlyCharges'] > 80)
df['Churn'] = np.where(high_churn,
                       np.random.choice(['Yes', 'No'], n_samples, p=[0.75, 0.25]),
                       np.random.choice(['Yes', 'No'], n_samples, p=[0.20, 0.80]))

print(f"Total records: {df.shape[0]}")
print("Sample data:\n", df.head(5))
print("\nChurn distribution:\n", df['Churn'].value_counts())

# ====================== STEP 2: Prepare Features (X) and Target (y) ======================
X = df.drop('Churn', axis=1)   # All columns except target
y = df['Churn']

categorical_features = ['Gender', 'Contract', 'PaymentMethod', 'InternetService']
numerical_features   = ['Tenure', 'MonthlyCharges']
# Note: CustomerFeedback is automatically dropped because we don't include it below

# ====================== STEP 3: Create Preprocessor with OneHotEncoder ======================
print("\n=== STEP 3: Creating preprocessor with One-Hot Encoding ===")

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),                    # Scale numbers
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)  # One-Hot Encoding
    ],
    remainder='drop'   # This drops CustomerFeedback column
)

# ====================== STEP 4: Create Full Pipeline ======================
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# ====================== STEP 5: Train-Test Split (80% train, 20% test) ======================
print("\n=== STEP 5: Splitting data into train and test ===")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)
print(f"Training records: {X_train.shape[0]} | Test records: {X_test.shape[0]}")

# ====================== STEP 6: Train the Model ======================
print("\n=== STEP 6: Training the model ===")
pipeline.fit(X_train, y_train)

# ====================== STEP 7: Evaluate on Test Data ======================
print("\n=== STEP 7: Checking accuracy on test data ===")
y_pred = pipeline.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"✅ Accuracy: {accuracy:.2%}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ====================== STEP 8: Predict on New Data (Future Use) ======================
print("\n=== STEP 8: Predicting on new customer data ===")
new_data = pd.DataFrame({
    'Gender': ['Female', 'Male'],
    'Contract': ['Two year', 'Month-to-month'],
    'PaymentMethod': ['Credit card', 'Electronic check'],
    'InternetService': ['DSL', 'Fiber optic'],
    'Tenure': [48, 5],
    'MonthlyCharges': [55.75, 95.50],
    'CustomerFeedback': ["Great service", "Poor connection"]   # ignored automatically
})

predictions = pipeline.predict(new_data)
probabilities = pipeline.predict_proba(new_data)

print("New Data:")
print(new_data)
print("\nPredictions:")
for i, (pred, prob) in enumerate(zip(predictions, probabilities)):
    print(f"Customer {i+1}: Churn = {pred} | Probability = {prob[1]:.2%}")

print("\n🎉 One-Hot Encoding Only script complete!")

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ====================== STEP 1: Generate 150 Records ======================
print("=== STEP 1: Generating 150 synthetic customer records ===")
np.random.seed(42)

n_samples = 150

data = {
    'Gender': np.random.choice(['Male', 'Female'], n_samples),
    'Contract': np.random.choice(['Month-to-month', 'One year', 'Two year'], n_samples, p=[0.55, 0.30, 0.15]),
    'PaymentMethod': np.random.choice(['Electronic check', 'Mailed check', 'Bank transfer', 'Credit card'], n_samples),
    'InternetService': np.random.choice(['DSL', 'Fiber optic', 'No'], n_samples, p=[0.35, 0.50, 0.15]),
    'Tenure': np.random.randint(1, 73, n_samples),
    'MonthlyCharges': np.round(np.random.uniform(20, 120, n_samples), 2),
    'CustomerFeedback': np.random.choice([
        "Great service", "Poor connection", "Excellent support", "Billing issues",
        "Love the pricing", "Slow internet", "Happy overall", "Too expensive"
    ], n_samples)
}

df = pd.DataFrame(data)
display(df.head())

=== STEP 1: Generating 150 synthetic customer records ===

,Gender,Contract,PaymentMethod,InternetService,Tenure,MonthlyCharges,CustomerFeedback
0,Male,One year,Mailed check,DSL,61,32.80,Happy overall
1,Female,One year,Mailed check,Fiber optic,54,35.19,Too expensive
2,Male,Month-to-month,Mailed check,Fiber optic,39,33.88,Slow internet
3,Male,Month-to-month,Mailed check,Fiber optic,19,84.09,Too expensive
4,Male,Month-to-month,Electronic check,Fiber optic,39,38.19,Excellent support

In [21]:
high_churn = (df['Tenure'] < 12) | (df['MonthlyCharges'] > 80)
high_churn

0      False
1      False
2      False
3       True
4      False
       ...
145     True
146    False
147     True
148    False
149     True
Length: 150, dtype: bool

In [24]:
df['Churn'] = np.where(high_churn,
                       np.random.choice(['Yes', 'No'], n_samples, p=[0.75, 0.25]),
                       np.random.choice(['Yes', 'No'], n_samples, p=[0.20, 0.80]))

print(f"Total records: {df.shape[0]}")
display(df.head())
print("\nChurn distribution:\n", df['Churn'].value_counts())

Total records: 150

,Gender,Contract,PaymentMethod,InternetService,Tenure,MonthlyCharges,CustomerFeedback,Churn
0,Male,One year,Mailed check,DSL,61,32.80,Happy overall,No
1,Female,One year,Mailed check,Fiber optic,54,35.19,Too expensive,No
2,Male,Month-to-month,Mailed check,Fiber optic,39,33.88,Slow internet,No
3,Male,Month-to-month,Mailed check,Fiber optic,19,84.09,Too expensive,Yes
4,Male,Month-to-month,Electronic check,Fiber optic,39,38.19,Excellent support,Yes

Churn distribution:
 Churn
No     85
Yes    65
Name: count, dtype: int64

In [25]:
X = df.drop('Churn', axis=1)   # All columns except target
X

,Gender,Contract,PaymentMethod,InternetService,Tenure,MonthlyCharges,CustomerFeedback
0,Male,One year,Mailed check,DSL,61,32.80,Happy overall
1,Female,One year,Mailed check,Fiber optic,54,35.19,Too expensive
2,Male,Month-to-month,Mailed check,Fiber optic,39,33.88,Slow internet
3,Male,Month-to-month,Mailed check,Fiber optic,19,84.09,Too expensive
4,Male,Month-to-month,Electronic check,Fiber optic,39,38.19,Excellent support
...,...,...,...,...,...,...,...
145,Male,One year,Credit card,No,6,72.31,Poor connection
146,Male,One year,Electronic check,No,53,55.88,Slow internet
147,Male,Month-to-month,Bank transfer,Fiber optic,66,107.72,Billing issues
148,Male,Month-to-month,Credit card,Fiber optic,43,59.24,Slow internet
149,Female,Month-to-month,Mailed check,DSL,23,101.66,Happy overall

In [26]:
y = df['Churn']
y

0       No
1       No
2       No
3      Yes
4      Yes
      ...
145     No
146     No
147    Yes
148    Yes
149     No
Name: Churn, Length: 150, dtype: str

In [27]:
categorical_features = ['Gender', 'Contract', 'PaymentMethod', 'InternetService']
numerical_features   = ['Tenure', 'MonthlyCharges']

In [47]:
# ====================== STEP 3: Create Preprocessor with OneHotEncoder ======================
print("\n=== STEP 3: Creating preprocessor with One-Hot Encoding ===")
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),                    # Scale numbers
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)  # One-Hot Encoding
    ],
    remainder='drop'   # This drops CustomerFeedback column
)
preprocessor

=== STEP 3: Creating preprocessor with One-Hot Encoding ===

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['Tenure', 'MonthlyCharges']),
                                ('cat',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['Gender', 'Contract', 'PaymentMethod',
                                  'InternetService'])])

In [29]:
# ====================== STEP 4: Create Full Pipeline ======================
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])
pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Tenure', 'MonthlyCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Gender', 'Contract',
                                                   'PaymentMethod',
                                                   'InternetService'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [30]:
# ====================== STEP 5: Train-Test Split (80% train, 20% test) ======================
print("\n=== STEP 5: Splitting data into train and test ===")

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)
X_train

=== STEP 5: Splitting data into train and test ===

,Gender,Contract,PaymentMethod,InternetService,Tenure,MonthlyCharges,CustomerFeedback
120,Female,Month-to-month,Mailed check,Fiber optic,47,45.46,Billing issues
40,Male,Two year,Credit card,Fiber optic,1,23.67,Happy overall
8,Male,Month-to-month,Bank transfer,Fiber optic,58,86.76,Happy overall
14,Female,Month-to-month,Credit card,Fiber optic,3,37.70,Great service
109,Male,Month-to-month,Mailed check,DSL,26,78.12,Poor connection
...,...,...,...,...,...,...,...
101,Female,One year,Credit card,No,45,38.70,Poor connection
89,Female,Month-to-month,Mailed check,Fiber optic,55,59.79,Excellent support
95,Female,One year,Credit card,No,23,86.86,Too expensive
87,Male,One year,Bank transfer,DSL,1,118.24,Poor connection
64,Male,Two year,Mailed check,No,13,78.68,Happy overall

In [31]:
X_test

,Gender,Contract,PaymentMethod,InternetService,Tenure,MonthlyCharges,CustomerFeedback
60,Male,Month-to-month,Electronic check,Fiber optic,63,98.92,Great service
139,Male,One year,Electronic check,DSL,10,99.53,Excellent support
144,Female,One year,Credit card,Fiber optic,34,86.52,Love the pricing
85,Male,Month-to-month,Mailed check,Fiber optic,49,72.45,Billing issues
102,Female,Month-to-month,Electronic check,Fiber optic,4,52.37,Slow internet
99,Male,One year,Bank transfer,Fiber optic,1,48.00,Happy overall
32,Female,One year,Electronic check,DSL,20,38.45,Too expensive
39,Male,One year,Electronic check,DSL,31,94.75,Slow internet
3,Male,Month-to-month,Mailed check,Fiber optic,19,84.09,Too expensive
22,Female,Month-to-month,Bank transfer,Fiber optic,58,23.93,Excellent support
1,Female,One year,Mailed check,Fiber optic,54,35.19,Too expensive
33,Female,Month-to-month,Mailed check,DSL,57,40.93,Billing issues
62,Male,One year,Bank transfer,Fiber optic,33,28.69,Slow internet
118,Female,One year,Bank transfer,Fiber optic,57,52.24,Billing issues
61,Male,Month-to-month,Mailed check,Fiber optic,17,69.84,Slow internet
123,Male,Two year,Mailed check,Fiber optic,66,79.56,Love the pricing
135,Male,Month-to-month,Bank transfer,Fiber optic,51,94.11,Slow internet
2,Male,Month-to-month,Mailed check,Fiber optic,39,33.88,Slow internet
148,Male,Month-to-month,Credit card,Fiber optic,43,59.24,Slow internet
48,Female,Month-to-month,Electronic check,Fiber optic,24,73.26,Love the pricing
124,Male,One year,Bank transfer,DSL,51,67.16,Too expensive
113,Female,Month-to-month,Bank transfer,Fiber optic,50,25.18,Too expensive
98,Female,Month-to-month,Mailed check,Fiber optic,17,77.16,Too expensive
104,Female,Month-to-month,Electronic check,DSL,65,70.76,Billing issues
84,Male,One year,Bank transfer,Fiber optic,27,28.02,Excellent support
24,Female,Month-to-month,Bank transfer,No,45,82.79,Excellent support
36,Female,Month-to-month,Bank transfer,No,49,81.83,Love the pricing
138,Male,Month-to-month,Credit card,Fiber optic,4,33.98,Slow internet
74,Male,Month-to-month,Mailed check,DSL,30,80.58,Love the pricing
19,Male,One year,Credit card,DSL,33,56.43,Love the pricing

In [33]:
y_train

120     No
40     Yes
8      Yes
14      No
109     No
      ...
101     No
89      No
95     Yes
87     Yes
64      No
Name: Churn, Length: 120, dtype: str

In [34]:
y_test

60     Yes
139     No
144    Yes
85      No
102    Yes
99      No
32      No
39      No
3      Yes
22     Yes
1       No
33      No
62      No
118     No
61     Yes
123     No
135    Yes
2       No
148    Yes
48      No
124     No
113    Yes
98      No
104     No
84      No
24     Yes
36     Yes
138    Yes
74     Yes
19      No
Name: Churn, dtype: str

In [35]:
# ====================== STEP 6: Train the Model ======================
print("\n=== STEP 6: Training the model ===")
pipeline.fit(X_train, y_train)

=== STEP 6: Training the model ===

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Tenure', 'MonthlyCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Gender', 'Contract',
                                                   'PaymentMethod',
                                                   'InternetService'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [36]:
# ====================== STEP 7: Evaluate on Test Data ======================
print("\n=== STEP 7: Checking accuracy on test data ===")
y_pred = pipeline.predict(X_test)
y_pred

=== STEP 7: Checking accuracy on test data ===

array(['Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No'],
      dtype=object)

In [38]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"✅ Accuracy: {accuracy:.2%}")

✅ Accuracy: 63.33%

In [39]:
from sklearn.metrics import classification_report

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

          No       0.64      0.82      0.72        17
         Yes       0.62      0.38      0.48        13

    accuracy                           0.63        30
   macro avg       0.63      0.60      0.60        30
weighted avg       0.63      0.63      0.61        30

In [40]:
from sklearn.metrics import confusion_matrix

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[14  3]
 [ 8  5]]

- Testing the Trained Model with sample data

In [41]:
print("\n=== STEP 8: Predicting on new customer data ===")
new_data = pd.DataFrame({
    'Gender': ['Female', 'Male'],
    'Contract': ['Two year', 'Month-to-month'],
    'PaymentMethod': ['Credit card', 'Electronic check'],
    'InternetService': ['DSL', 'Fiber optic'],
    'Tenure': [48, 5],
    'MonthlyCharges': [55.75, 95.50],
    'CustomerFeedback': ["Great service", "Poor connection"]   # ignored automatically
})
new_data

=== STEP 8: Predicting on new customer data ===

,Gender,Contract,PaymentMethod,InternetService,Tenure,MonthlyCharges,CustomerFeedback
0,Female,Two year,Credit card,DSL,48,55.75,Great service
1,Male,Month-to-month,Electronic check,Fiber optic,5,95.50,Poor connection

In [42]:
predictions = pipeline.predict(new_data)
predictions

array(['No', 'Yes'], dtype=object)

In [43]:
probabilities = pipeline.predict_proba(new_data)
probabilities

array([[0.73, 0.27],
       [0.25, 0.75]])

In [46]:
print("New Data:")
print(new_data)
print("\nPredictions:")
for i, (pred, prob) in enumerate(zip(predictions, probabilities)):
    print(f"Customer {i+1}: Churn = {pred} | Probability = {prob[1]:.2%}")

print("\n🎉 One-Hot Encoding Only script complete!")

New Data:
   Gender        Contract     PaymentMethod InternetService  Tenure  \
0  Female        Two year       Credit card             DSL      48
1    Male  Month-to-month  Electronic check     Fiber optic       5

   MonthlyCharges CustomerFeedback
0           55.75    Great service
1           95.50  Poor connection

Predictions:
Customer 1: Churn = No | Probability = 27.00%
Customer 2: Churn = Yes | Probability = 75.00%

🎉 One-Hot Encoding Only script complete!